package block

import (
	"dgc/util"
	"testing"
	"time"
)

// TestGenesisBlock checks the creation of the genesis block
func TestGenesisBlock(t *testing.T) {
	genesisBlock := Genesis()

	if genesisBlock.Timestamp == 0 {
		t.Error("Genesis block timestamp should not be zero")
	}

	if genesisBlock.LastHash != "-----" {
		t.Error("Genesis block LastHash should be '-----'")
	}

	if len(genesisBlock.Data) != 0 {
		t.Error("Genesis block Data should be empty")
	}
}

// TestMineBlock checks the mining of a new block
func TestMineBlock(t *testing.T) {
	genesisBlock := Genesis()
	data := []string{"Some transaction data"}
	newBlock := MineBlock(genesisBlock, data)

	if newBlock.Timestamp == 0 {
		t.Error("Mined block timestamp should not be zero")
	}

	if newBlock.LastHash != genesisBlock.Hash {
		t.Error("Mined block LastHash should match the previous block's hash")
	}

	if len(newBlock.Data) != len(data) {
		t.Error("Mined block Data should match the input data")
	}

	if newBlock.Nonce == 0 {
		t.Error("Mined block should have a non-zero nonce")
	}
}

// TestBlockHash checks that block hash is generated correctly
func TestBlockHash(t *testing.T) {
	genesisBlock := Genesis()
	data := []string{"Some transaction data"}
	newBlock := MineBlock(genesisBlock, data)

	hash1 := newBlock.BlockHash()
	hash2 := Hash(newBlock.Timestamp, newBlock.LastHash, newBlock.Data, newBlock.Nonce, newBlock.Difficulty)

	if hash1 != hash2 {
		t.Errorf("Block hash generated by blockHash and Hash do not match. Got %s, expected %s", hash1, hash2)
	}
}

func TestAdjustDifficulty(t *testing.T) {
	lastBlock := Block{Timestamp: time.Now().Unix(), Difficulty: util.DIFFICULTY}
	currentTime := time.Now().Unix() + 5000 // time after MINE_RATE

	newDifficulty := AdjustDifficulty(lastBlock, currentTime)
	if newDifficulty == util.DIFFICULTY {
		t.Error("Expected difficulty to change after adjusting.")
	}
}
